### ISSUE TITLE
Fix Turret Watchdog

### ISSUE THREAD

**Issue by karkason** [frc3316/Stronghold2016#13]
Make the StopTurret a continuous command, to make the scheduler like us:
- Change the isFinished return value to true
- Move the setMotors to execute

**Comment by MrAlpaca** [comment]
Stop turret is set to be the default command, so it will get restarted every run of the scheduler if we change the return value to true. It depends on how we perceive its functionality:
- The watchdog is supposed to execute the line "setMotors(0)" in case a previous command finished and didn't call it (for example because a programmer forgot to add it); or
- The watchdog is a cancel command which we use in sequences.

Which one are you aiming for?

**Comment by karkason** [comment]
You're right. I thought the isFinished return value was the other way around. Oops.
The watchdog must be used by your first usage, but can also be used as a cancel command. Both seem valid.

I'm closing the issue because it makes no sense.
